
variable "aws_access_key" {
  type    = string
  default = ""
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "aws_secret_key" {
  type    = string
  default = ""
}

variable "source_ami" {
  type    = string
  default = "ami-033b95fb8079dc481"
}

variable "ssh_username" {
  type    = string
  default = "ec2-user"
}

variable "subnet_id" {
  type    = string
  default = "subnet-0dd19433a35a966a5"
}

variable "github_repo" {
  default = env("GITHUB_REPO_PATH")
}

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }


source "amazon-ebs" "autogenerated_1" {
  access_key      = "${var.aws_access_key}"
  ami_description = "Linux AMI for CSYE6225"
  ami_name        = "csye6225_ami_${local.timestamp}"
  ami_users       = [359984899562, 342617959621]
  instance_type   = "t2.micro"
  launch_block_device_mappings {
    delete_on_termination = true
    device_name           = "/dev/xvda"
    volume_size           = 8
    volume_type           = "gp2"
  }
  region       = "${var.aws_region}"
  secret_key   = "${var.aws_secret_key}"
  source_ami   = "${var.source_ami}"
  ssh_username = "${var.ssh_username}"
  subnet_id    = "${var.subnet_id}"
}


build {
  sources = ["source.amazon-ebs.autogenerated_1"]

   provisioner "file" {
      destination = "/tmp/webservice.tar"
      source      = "${var.github_repo}/appDir/webservice.tar"
  }

  provisioner "shell" {
    script = "app-server.sh"
  }

}
