version: 0.0
os: linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# giving permission to files and folders to centos user in home directory
files:
  - source: /
    destination: /home/ubuntu/webservice

hooks:

  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 600
      runas: ec2-user
