version: 0.0
os: linux
# giving permission to files and folders to centos user in home directory
files:
  - source: /
    destination: /home/ec2-user/webservice
hooks:
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ec2-user
