name: CI - Unit Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a set of commands using the runners shell
      - name: NPM tests
        run: |
          cd api
          pwd
          npm ci
          echo "PWD: $(pwd)"
          ls -ltr

      - name: Zip the file
        run: |
          echo "PWD: $(pwd)"
          cd ../
          zip -cf webservice.zip webservice
          ls -l
          echo "PWD: $(pwd)"
          cd webservice
          echo "mkdir"; mkdir appDir
          cp ../webservice.zip appDir
          ls -l appDir          

          
      # Packer validation and ami creation
      - name: Init Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ./ami.json.pkr.hcl
      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ./ami.json.pkr.hcl
      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GH_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Copying artifact to S3
        run: |
          rm -rf aws
          aws deploy push --application-name csye6225webapp --description "Copying the latest revision for csye6225webapplication-${{ github.sha }}.zip" --ignore-hidden-files --s3-location s3://${{secrets.CODEDEPLOY_BUCKET}}/csye6225-webapplication-${{ github.sha}}.zip  --source .
      - name: Using code deploy
        run: |
          aws deploy create-deployment --application-name csye6225webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --file-exists-behavior OVERWRITE --s3-location bucket=${{secrets.CODEDEPLOY_BUCKET}},key=csye6225-webapplication-${{ github.sha }}.zip,bundleType=zip
        env:
          PACKER_LOG: 1
          GITHUB_REPO_PATH: ${{ github.workspace }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_CODEDEPLOY_BUCKET: ${{secrets.CODEDEPLOY_BUCKET}}