name: Validate
on:
  pull_request:
    branches: [ main ]
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a set of commands using the runners shell
      - name: NPM tests
        run: |
          pwd
          npm i
          echo "PWD: $(pwd)"
          ls -ltr
      # Packer template validation
      - name: Init Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ./ami.json.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PACKER_LOG: 1